{% set version = "2.3.2" %}
{% set name = "fflas-ffpack" %}
{% set variant = "openblas" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/linbox-team/fflas-ffpack/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: c0c7426a983d961d75c61638be9406a74415b429251e5d4295ee1110d1ee0e69
  patches:
  - patches/dont-sort-cxxflags.patch

build:
  number: 0
  skip: true  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - toolchain
    - libtool
    - pkg-config
    - givaro >=4.0.3,<5
    - gsl
    - gmp 6.1.*
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - automake
  run:
    - givaro >=4.0.3,<5
    - gsl
    - gmp >=6.1,<7
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*

test:
  commands:
    - test -f ${PREFIX}/include/fflas-ffpack/ffpack/ffpack.h
    - test -f ${PREFIX}/lib/libfflas.dylib      # [osx]
    - test -f ${PREFIX}/lib/libfflas.so         # [linux]
    - test -f ${PREFIX}/lib/libffpack.dylib     # [osx]
    - test -f ${PREFIX}/lib/libffpack.so        # [linux]

about:
  home: http://linbox-team.github.io/fflas-ffpack/
  license: LGPLv2.1+
  license_file: COPYING.LESSER
  summary: Finite Field Linear Algebra Subroutines / Package
  dev_url: https://github.com/linbox-team/fflas-ffpack

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
